---
title: Error Handling
description: ShipEngine Connect applications can throw errors just like any other JavaScript application. We also support custom error properties and classes to make things easier.
---

# Error Handling

[ShipEngine Connect](../index.mdx) applications use error objects defined in the `@shipengine/connect-runtime` package to determine when an error was thrown intentionally by the implementor.

Any uncaught exception will terminate the currently executing method and generate an error log.

For example, the methods you implement will often need to perform input validation. If this validation fails, you can throw an error as in the example below.

## Bad Request Error

This type of error means that the user has submitted some information in their request that is causing the function to fail.
This allows the user to know that if they change something about their request it could be successful.

```javascript highlight=5
import { BadRequestError } from "@shipengine/connect-runtime";
// ...
for (let package of request.packages) {
  if (
    package.package_code === "BOX" &&
    package.weight_details.weight_in_grams > 100000
  ) {
    throw new BadRequestError(
      `${package.package_code} cannot weigh more than 100 kilograms`
    );
  }
}
```

<Reference>
  <Field name="message" type="string">
    <Description>
      This is the message that will be displayed to the end users of the
      platform.
    </Description>
  </Field>
  <Field name="details">
    <Type>[ErrorDetail](#error-detail) | [ErrorDetail](#error-detail)[]</Type>
    <Description>
      This contains additional information that needs to be logged along side
      the error.
    </Description>
  </Field>
</Reference>

## Unauthorized Error

This error lets a user know that they need to update their credentials in order to continue using their connection.

```javascript highlight=5
import { UnauthorizedError } from "@shipengine/connect-runtime";
// ...
const response = await axios.post(THIRD_PARTY_API_URL, { credentials });
if (response.statusCode === 401) {
  throw new UnauthorizedError("Invalid Credentials");
}
```

<Reference>
  <Field name="message" type="string">
    <Description>
      This is the message that will be displayed to the end users of the
      platform.
    </Description>
  </Field>
  <Field name="details">
    <Type>[ErrorDetail](#error-detail) | [ErrorDetail](#error-detail)[]</Type>
    <Description>
      This contains additional information that needs to be logged along side
      the error.
    </Description>
  </Field>
</Reference>
## External Server Error

This type of error lets the user know that there is an issue with the outside world that we cannot resolve.

```javascript highlight=5
import { ExternalServerError } from "@shipengine/connect-runtime";
// ...
const response = await axios.post(THIRD_PARTY_API_URL, { credentials });
if (response.statusCode > 500) {
  throw new ExternalServerError(
    "There was an issue with the third parties api."
  );
}
```

<Reference>
  <Field name="message" type="string">
    <Description>
      This is the message that will be displayed to the end users of the
      platform.
    </Description>
  </Field>
  <Field name="details">
    <Type>[ErrorDetail](#error-detail) | [ErrorDetail](#error-detail)[]</Type>
    <Description>
      This contains additional information that needs to be logged along side
      the error.
    </Description>
  </Field>
</Reference>
## Rate Limit Error

This lets the platform know that it should hold off on making more calls due to Rate Limiting by the third party.

```javascript highlight=5
import { RateLimitError } from "@shipengine/connect-runtime";
// ...
const response = await axios.post(THIRD_PARTY_API_URL, { credentials });
if (response.statusCode === 429) {
  throw new RateLimitError(
    "Too many requests were made to the third parties apis.",
    {
      retryAfterSeconds: response.body.retry_after,
      throttlingContext: response.body,
    }
  );
}
```

<Reference>
  <Field name="message" type="string">
    <Description>
      This is the message that will be displayed to the end users of the
      platform.
    </Description>
  </Field>
  <Field name="details">
    <Type>object</Type>
    <Description>
      This contains additional information related to a rate limiting error.
    </Description>
  </Field>
  <Field name="details.retryAfterSeconds">
    <Type>number</Type>
    <Description>
      The number of seconds the platform should wait before making another
      request.
    </Description>
  </Field>
  <Field name="details.retryAfterTime">
    <Type>string</Type>
    <Description>
      The time the platform should wait for until it makes it's next
      request.[`ISO-8601`](https://en.wikipedia.org/wiki/ISO_8601)
    </Description>
  </Field>
  <Field name="details.throttlingContext">
    <Type>any</Type>
    <Description>
      Any additional information that could be beneficial to see in the logs.
      (Could be the full body of the response)
    </Description>
  </Field>
</Reference>
## Error Detail

Along with the base error message that can be set when throwing a new error, you also have the option of passing in additional properties through an ErrorDetail object or Array of ErrorDetail objects.
Lets take a look at the previous example of throwing a bad request error, but lets add some more detailed information for logging purposes.

```javascript highlight=5
import { BadRequestError } from "@shipengine/connect-runtime";
// ...
const response = await axios.post(THIRD_PARTY_API_URL, { credentials });
if (response.statusCode === 400) {
  throw new BadRequestError("There was an issue with the third parties api.", {
    externalErrorCode: response.body.custom_third_party_error_code,
    message: response.body.custom_error_message,
    externalHttpStatusCode: 400,
    externalContext: response.body,
    errorCode: StandardizedErrorCode.ExternalClientError,
  });
}
```

Now when we see logs this new information will appear alongside the original error message, but will not be displayed to the end users.

<Reference>
  <Field name="externalErrorCode" type="string">
    <Description>
      This is the error code that is specific to the third party Ex: `AMAZ_2324,
      SHOP_3435`. This can be useful for our support to help diagnose issues.
    </Description>
  </Field>
  <Field name="message" type="string">
    <Description>Any message that needs to be associated with this detail.</Description>
  </Field>
  <Field name="externalHttpStatusCode" type="number">
    <Description>The http status code returned by the third parties request.</Description>
  </Field>
  <Field name="externalContext" type="string">
    <Description>Any additional information that would be useful to log in the error.</Description>
  </Field>
  <Field name="errorCode" type="string">
    <Description>An optional standarized error code associated with this detail. `Generic`, `Validation`, `Unauthorized`, `ExternalServerError`, `ExternalClientError`</Description>
  </Field>
</Reference>
<Pager
  prev="./typescript.mdx"
  prevTitle="Developing in TypeScript"
  next="./testing/index.mdx"
  nextTitle="Testing"
/>
